[build-system]
requires = ["setuptools>=61"]
build-backend = "setuptools.build_meta"

[project]
name = "chemicalgof"
version = "0.3.0.dev0"
description = "fragSMILES, fragment-based chemical notation from graph reduction process."
readme = "README.md"
requires-python = ">=3.13"
license = { file = "LICENSE" }

authors = [
    { name = "Fabrizio Mastrolorito", email = "fabrizio.mastrolorito@uniba.it" }
]

dependencies = [
    "rdkit>=2026",
    "networkx>=3.6",
    "numpy>=2.0",
    "pandas>=3.0",
    "matplotlib>=3",
]

[project.urls]
Homepage = "https://github.com/f48r1/chemicalgof"
Repository = "https://github.com/f48r1/chemicalgof"

[tool.setuptools.packages.find]
include = ["chemicalgof*"]